# Generated by Django 4.0.3 on 2022-03-16 03:07

import assetsapp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Area Name')),
            ],
            options={
                'verbose_name_plural': 'Areas',
                'db_table': 'areas',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('email', models.EmailField(blank=True, max_length=60, null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name_plural': 'Persons',
                'db_table': 'persons',
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Asset Name')),
                ('serial', models.CharField(max_length=60, verbose_name='Serial')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[assetsapp.models.validate_negative], verbose_name='Purchase Price')),
                ('purchase_date', models.DateField(validators=[assetsapp.models.validate_future_date], verbose_name='Purchase date')),
                ('leaving_date', models.DateField(blank=True, default=None, null=True, validators=[assetsapp.models.validate_future_date], verbose_name='Leaving Date')),
                ('current_status', models.CharField(choices=[('AV', 'Available'), ('RE', 'Retired'), ('UR', 'Under Repair'), ('AS', 'Assigned')], max_length=2)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assetsapp.area')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assetsapp.person')),
            ],
            options={
                'verbose_name_plural': 'Assets',
                'db_table': 'assets',
            },
        ),
    ]
