# Generated by Django 4.0.3 on 2022-03-16 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assetsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assetsapp.area'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='current_status',
            field=models.CharField(choices=[('AV', 'Available'), ('RE', 'Retired'), ('UR', 'Under Repair'), ('AS', 'Assigned')], max_length=2, verbose_name='Current Status'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assetsapp.person'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='serial',
            field=models.CharField(max_length=60, unique=True, verbose_name='Serial'),
        ),
    ]
